### ISSUE TITLE
Target in repo

### ISSUE THREAD

**Issue by Ddystopia** [fiit-ba/rust-course#1]
Hello, you have pushed target directory to repository. It increases `.git` size and slows down clones/any work with repo. Could you please erase it from history (git filter or something like that) and force push the repo? Thanks

**Comment by xkostal** [comment]
Done, however not through filter, but just basic cleaning for lack of time. Thank you and sorry for this mistake :)

**Comment by xkostal** [comment]
The commit c9b4279 solved the issue
